### ISSUE TITLE
There is no package called mqbackend

### ISSUE THREAD

**Issue by WynnDing** [mindspore-ai/mindquantum#1]
in parameterresolver.py
from mindquantum import mqbackend as mb

**Comment by ducknificient** [comment]
is this already fixed ?
```
pip3.10 show mindquantum
Name: mindquantum
Version: 0.10.0
Summary: A hybrid quantum-classic framework for quantum computing
Home-page: 
Author: 
Author-email: The MindSpore Authors <contact@mindspore.cn>
License: Apache License Version 2.0
Location: /home/spil/.local/lib/python3.10/site-packages
Requires: matplotlib, rich, scipy
Required-by: 

```
```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
tyro 0.8.4 requires rich>=11.1.0, but you have rich 10.9.0 which is incompatible.
typer 0.12.3 requires rich>=10.11.0, but you have rich 10.9.0 which is incompatible.
manim 0.18.1 requires rich>=12.0.0, but you have rich 10.9.0 which is incompatible.
```
```
python3.10 -c 'import mindquantum'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/spil/.local/lib/python3.10/site-packages/mindquantum/__init__.py", line 23, in <module>
    from .mqbackend import logging
ModuleNotFoundError: No module named 'mindquantum.mqbackend'
```

**Comment by ducknificient** [comment]
also this is an error when built from source
```
creating /home/user/.local/lib/python3.10/site-packages/UNKNOWN-0.0.0-py3.10-linux-x86_64.egg
Extracting UNKNOWN-0.0.0-py3.10-linux-x86_64.egg to /home/user/.local/lib/python3.10/site-packages
Adding UNKNOWN 0.0.0 to easy-install.pth file

Installed /home/user/.local/lib/python3.10/site-packages/UNKNOWN-0.0.0-py3.10-linux-x86_64.egg
error: The 'projectq>=0.5.1' distribution was not found and is required by mindquantum
```
